#!/usr/bin/bash

export RUSTFLAGS=-Cforce-frame-pointers=yes

pushd ../casper-node
cargo build --release --package casper-node
cargo build --release --package casper-client
popd

pushd ../casper-node-launcher
cargo build --release
popd

pushd ../casper-node
make build-contract-rs/add-bid
make build-contract-rs/delegate
make build-contract-rs/transfer-to-account-u512
make build-contract-rs/transfer-to-account-u512-stored
make build-contract-rs/undelegate
make build-contract-rs/withdraw-bid
popd
