- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  gather_facts: no
  tasks:

      - name: "removing /storage/{{ inventory_hostname }}/"
        file:
          state: absent
          path: "/storage/{{ inventory_hostname }}/"

      - name: Truncating syslog
        shell: "> /var/log/syslog"

      - name: Get list of syslog files for deletion
        shell: find /var/log -maxdepth 1 -name "syslog.*"
        register: syslog_files

      - name: Removing syslogs
        file:
            path: "{{item}}"
            state: absent
        with_items: "{{ syslog_files.stdout_lines }}"

