- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  gather_facts: no
  tasks:
      - name: Stopping casper-node.service
        service:
          name: casper-node.service
          enabled: yes
          state: stopped

      - name: Stopping casper-node-heaptracked.service
        service:
          name: casper-node-heaptracked.service
          enabled: yes
          state: stopped

      - name: Removing /var/lib/casper
        file:
          state: absent
          path: /var/lib/casper/

      - name: Removing /etc/casper
        file:
          state: absent
          path: /etc/casper/

      - name: "removing /storage/{{ inventory_hostname }}/"
        file:
          state: absent
          path: "/storage/{{ inventory_hostname }}/"

      - name: Truncating syslog
        shell: "> /var/log/syslog"

      - name: Get list of syslog files for deletion
        shell: find /var/log -maxdepth 1 -name "syslog.*"
        register: syslog_files

      - name: Removing syslogs
        file:
            path: "{{item}}"
            state: absent
        with_items: "{{ syslog_files.stdout_lines }}"

      - name: Get list of heaptrack files
        shell: find / -maxdepth 1 -name "heaptrack.casper-node.*.gz"
        register: path_files

      - name: Removing profiling data for heaptrack
        file:
            path: "{{item}}"
            state: absent
        with_items: "{{ path_files.stdout_lines }}"

