- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  tasks:
      - name: Stopping casper-node.service
        service:
          name: casper-node.service
          enabled: yes
          state: stopped

      - name: Removing /var/lib/casper
        file:
          state: absent
          path: /var/lib/casper/

      - name: Removing /etc/casper
        file:
          state: absent
          path: /etc/casper/

      - name: "removing /storage/{{ inventory_hostname }}/"
        file:
          state: absent
          path: "/storage/{{ inventory_hostname }}/"

      - name: Removing rotated syslogs
        shell: "/bin/rm -f /var/log/syslog.*"

      - name: Truncating syslog
        shell: "> /var/log/syslog"
