- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  gather_facts: no
  tasks:
      - name: Stopping casper-node.service
        service:
          name: casper-node.service
          enabled: yes
          state: stopped

      - name: Stopping casper-node-heaptracked.service
        service:
          name: casper-node-heaptracked.service
          enabled: yes
          state: stopped

      - name: Removing /var/lib/casper
        file:
          state: absent
          path: /var/lib/casper/

      - name: Removing /etc/casper
        file:
          state: absent
          path: /etc/casper/

      - name: "removing /storage/{{ inventory_hostname }}/"
        file:
          state: absent
          path: "/storage/{{ inventory_hostname }}/"

      - name: Removing rotated syslogs
        shell: "/bin/rm -f /var/log/syslog.*"

      - name: Truncating syslog
        shell: "> /var/log/syslog"

      - name: Get list of heaptrack files for download
        shell: ls /heaptrack.*.gz
        register: path_files

      - name: Removing profiling data for heaptrack
        file:
            path: "{{item}}"
            state: absent
        with_items: "{{ path_files.stdout_lines }}"
