- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  tasks:
      - name: Deploy casper binaries
        copy:
          src: "{{ chain_path }}/staging/bin"
          dest: /var/lib/casper
          mode: '777'

      - name: Deploying chainspec and config
        copy:
          src: "{{ chain_path }}/nodes/{{ inventory_hostname }}/etc/casper"
          dest: /etc/
          group: ubuntu

      - name: Deploying casper-node.service file
        copy:
          src: "templates/casper-node.service"
          dest: /etc/systemd/system/casper-node.service

      - name: Deploying casper-node-heaptracked.service file
        copy:
          src: "templates/casper-node-heaptracked.service"
          dest: /etc/systemd/system/casper-node-heaptracked.service

      - name: Reloading systemd
        systemd:
          daemon_reload: true
