- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  tasks:
      - name: Deploying casper-node.service file
        copy:
          src: "templates/casper-node.service"
          dest: /etc/systemd/system/casper-node.service

      - name: Reloading systemd
        systemd:
          daemon_reload: true
