- hosts: "{{ fetch_hosts }}"
  user: ubuntu
  become: true
  gather_facts: no

  tasks:
      - name: Archive syslog
        archive:
            path: "/var/log/casper-node.log"
            dest: "/var/log/casper-node.log.bz2"
            format: bz2

      - name: Fetching syslog
        fetch:
            src: "/var/log/casper-node.log.bz2"
            dest: "logs/{{ inventory_hostname }}/"
