all:
    children:
        vpn_server:
            hosts:
                135.181.37.147:
        # known_nodes is used to generate the chainspec, and by ansible for deployment of it
        known_nodes:
            hosts:
                65.21.1.227:
                135.181.37.138:
                135.181.37.169:
                135.181.37.220:
