- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  gather_facts: no
  tasks:
      - apt:
          name:
              - heaptrack
              - gdb
              - valgrind
              - python3-pip
              - linux-tools-common
              - linux-tools-aws
              - linux-tools-5.4.0-1029-aws
              - pcp
              - libpcp-pmda3-dev
              - libpcp3-dev
              - apache2
          state: latest
          update_cache: yes

      - pip:
          name:
              - boto3
              - botocore

