- hosts: "{{ deploy_hosts }}"
  user: ubuntu
  become: true
  gather_facts: no
  tasks:

      - name: Stopping casper-node.service
        service:
          name: casper-node.service
          enabled: yes
          state: stopped
